# Generated by Django 4.1.5 on 2023-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_address_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=200)),
                ('BANKTXNID', models.BigIntegerField()),
                ('ORDERID', models.CharField(max_length=20, unique=True)),
                ('TXNAMOUNT', models.FloatField()),
                ('STATUS', models.CharField(max_length=50)),
                ('TXNTYPE', models.CharField(max_length=20)),
                ('PAYMENTMODE', models.CharField(max_length=200)),
                ('REFUNDAMT', models.FloatField()),
                ('TXNDATE', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
